### PR TITLE
Adjustments to the homepage template

### PR DESCRIPTION
**Pull request by waldyrious**
Hey @moba, nice work on the recent updates to the site — it looks amazing!

Here are some small tweaks to the homepage:
- Whitespace cleanup (8662241)
  - Fix indentation levels
  - Break paragraph with links into multiple lines
  - Add a blank line between the intro text and the content
- Content tweaks (50096f0)
  - Use regular font size in intro text (small font remains in the social media links paragraph)
  - Increase left margin of the logo a bit, and add alt text to it
  - style emphasized text using actual italics instead of underscores

You might want to review the diff of each commit independently, because the whitespace changes obscure the actual content changes, which are minor.

Let me know what you think!

### CODE REVIEW

**Comment by waldyrious** [comment]
Before-and-after screenshots:

## Desktop

| Before |
| ------ |
|  |

| After |
| ----- |
|  |

## Mobile

| Before | After |
| ------ | ----- |
|  |  |

**Comment by moba** [comment]
Hi @waldyrious! Happy to see that you are still around. :) Great work on the pull request, thank you for the effort! I like the changes and have merged them now, they should be live in a few minutes.

**Comment by moba** [comment]
Maybe it would even be a good idea to make the "large" logo smaller on mobile to avoid the unwieldy wrapping of the text.

**Comment by waldyrious** [comment]
Glad you liked it @moba!

And yeah, I did think the logo looked a bit too large on mobile. I'll try to cook up an improvement this weekend.

**Pull request merged**
