### PR TITLE
Improve styling of homepage in smaller screens

### PR DESCRIPTION
**Pull request by waldyrious**
Submitting the changes that were initially discussed [in #33](https://github.com/fossjobs/fossjobs/pull/33#issuecomment-762901806).

Depends on #34 — please merge that one first. This PR's branch actually has only one commit: 93e49ea.

### CODE REVIEW

**Comment by waldyrious** [comment]
Before-and-after screenshots:

| Before | After |
|:------:|:-----:|
|  |  |

**Comment by moba** [comment]
I have merged your cleanup work now so you can rebase. This looks great too, and basically ready to be merged as well! Highly appreciated work, thanks!

**Comment by waldyrious** [comment]
Alright, PR rebased!

**Comment by moba** [comment]
It's live now, and looks great :) Thanks again!

**Pull request merged**
